language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t hasancutcu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hasancutcu/react-test npm test -- --coverage

after_success:
  - docker build -t hasancutcu/multi-client ./client
  - docker build -t hasancutcu/multi-nginx ./nginx
  - docker build -t hasancutcu/multi-server ./server
  - docker build -t hasancutcu/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push hasancutcu/multi-client
  - docker push hasancutcu/multi-nginx
  - docker push hasancutcu/multi-server
  - docker push hasancutcu/multi-worker
